export interface Neighborhood {
  slug:           string
  name:           string
  zip:            string
  area:           string
  avgCost:        number
  range:          string
  badge?:         'hot' | 'new'
  commonMaterial: string
  indexPct:       number  // 0–100, relative to max in dataset
  description:    string  // short for meta/OG; long-form content added per page
  highlights:     string[] // local roofing factors
}

export const neighborhoods: Neighborhood[] = [
  // ── Inner NW ──
  { slug: 'pearl-district',     name: "Pearl District",        zip: '97209', area: 'Inner NW',        avgCost: 10200, range: '$8k–$14k',   badge: 'hot', commonMaterial: 'Flat / TPO',       indexPct: 77,  description: 'Portland\'s premier urban district with high-density condos and commercial buildings. Flat roofing dominates.', highlights: ['High proportion of flat/TPO roofs on condos', 'Strict Pearl District design review for visible materials', 'Multiple specialist contractors compete — use our vetting'] },
  { slug: 'nob-hill',           name: "Nob Hill / NW District", zip: '97210', area: 'Inner NW',        avgCost: 9800,  range: '$7.5k–$13k', commonMaterial: 'Asphalt / Slate',  indexPct: 74,  description: 'Victorian and Craftsman homes requiring careful material matching and historic preservation awareness.', highlights: ['Older Victorian stock with steep pitches', 'Some homes require slate-matched asphalt', 'Tight access streets impact labour cost'] },
  { slug: 'slabtown',           name: "Slabtown",              zip: '97210', area: 'Inner NW',        avgCost: 9400,  range: '$7k–$13k',   badge: 'new', commonMaterial: 'Asphalt',          indexPct: 71,  description: 'Fast-growing residential neighbourhood with mix of new construction and converted industrial buildings.', highlights: ['New-build friendly — many contractors familiar with the area', 'Mix of flat and pitched roofs on newer homes', 'Strong demand: book early in spring'] },
  { slug: 'goose-hollow',       name: "Goose Hollow",          zip: '97201', area: 'SW Portland',     avgCost: 8900,  range: '$6.5k–$12k', commonMaterial: 'Asphalt',          indexPct: 67,  description: 'Transitional neighbourhood between downtown and the West Hills with varied housing stock.', highlights: ['Mix of 1920s–1970s construction', 'Moderate wind exposure from West Hills', 'Competitive contractor availability'] },
  { slug: 'south-portland',     name: "South Portland",        zip: '97201', area: 'SW Portland',     avgCost: 8600,  range: '$6k–$12k',   commonMaterial: 'Asphalt',          indexPct: 65,  description: 'Established residential area with predominantly mid-century homes and good contractor access.', highlights: ['Good highway access keeps labour costs lower', 'Many homes in 40–60 year re-roofing cycle', 'Standard asphalt shingle dominates'] },

  // ── Inner SE ──
  { slug: 'ladds-addition',     name: "Ladd's Addition",       zip: '97214', area: 'Inner SE',        avgCost: 10400, range: '$8k–$15k',   badge: 'hot', commonMaterial: 'Cedar / Asphalt',  indexPct: 79,  description: 'Portland\'s only historic district with diagonal street grid. Strict preservation rules apply to roofing materials.', highlights: ['National Historic Register — material changes require approval', 'Cedar shake common on original homes', 'Limited contractor pool with historic district experience'] },
  { slug: 'richmond',           name: "Richmond",              zip: '97214', area: 'Inner SE',        avgCost: 9100,  range: '$7k–$12k',   commonMaterial: 'Asphalt',          indexPct: 69,  description: 'Large diverse neighbourhood with strong Craftsman housing stock and active homeowner community.', highlights: ['Large Craftsman bungalow stock — 20–30 year re-roof cycle active', 'High homeowner awareness: expect informed questions', 'Competitive: multiple PDX roofers active here'] },
  { slug: 'sunnyside',          name: "Sunnyside",             zip: '97214', area: 'Inner SE',        avgCost: 8800,  range: '$6.5k–$12k', commonMaterial: 'Asphalt',          indexPct: 66,  description: 'Vibrant inner SE neighbourhood with a mix of Victorian, Craftsman and mid-century housing.', highlights: ['Dense urban lots — access can be tight', 'Active neighbourhood association', 'Standard asphalt shingle well-suited to microclimate'] },
  { slug: 'hawthorne',          name: "Hawthorne",             zip: '97202', area: 'Inner SE',        avgCost: 9200,  range: '$7k–$13k',   commonMaterial: 'Asphalt',          indexPct: 70,  description: 'One of Portland\'s best-known neighbourhoods with older housing stock on the cusp of re-roofing cycles.', highlights: ['High volume of homes entering 25-year replacement cycle', 'Moss and algae common — specify algae-resistant shingles', 'Street parking restrictions affect project logistics'] },
  { slug: 'division-clinton',   name: "Division-Clinton",      zip: '97202', area: 'Inner SE',        avgCost: 8700,  range: '$6.5k–$12k', commonMaterial: 'Asphalt',          indexPct: 66,  description: 'Dense residential corridor with high demand for roofing services and several active local contractors.', highlights: ['High density — neighbouring properties during work need protection', 'Contractor competition keeps pricing sharp', 'Rain exposure: superior underlayment recommended'] },

  // ── Outer SE ──
  { slug: 'woodstock',          name: "Woodstock",             zip: '97202', area: 'SE Portland',     avgCost: 8400,  range: '$6k–$11.5k', commonMaterial: 'Asphalt',          indexPct: 64,  description: 'Family-friendly SE neighbourhood with large lots and classic Portland housing stock.', highlights: ['Larger lots with tree cover — debris management important', 'Mid-tier market: quality asphalt best ROI', 'Good contractor access via Powell Blvd'] },
  { slug: 'sellwood-moreland',  name: "Sellwood-Moreland",     zip: '97202', area: 'SE Portland',     avgCost: 9600,  range: '$7.5k–$13k', badge: 'hot', commonMaterial: 'Asphalt Premium',  indexPct: 73,  description: 'Upmarket SE neighbourhood with high homeowner investment and strong demand for premium roofing.', highlights: ['Higher-end market with appetite for premium materials', 'Active re-roofing cycle on 1930s–50s homes', 'Proximity to river increases moisture — invest in quality underlayment'] },
  { slug: 'eastmoreland',       name: "Eastmoreland",          zip: '97202', area: 'SE Portland',     avgCost: 11200, range: '$8.5k–$16k', badge: 'hot', commonMaterial: 'Cedar / Premium',  indexPct: 85,  description: 'Affluent SE neighbourhood with large homes, mature trees and a market that demands premium materials and craftsmanship.', highlights: ['Premium market — cedar shake and metal strong here', 'Large roofs with complex geometry increase costs', 'High standard expected: use only top-rated PDX contractors'] },
  { slug: 'brooklyn',           name: "Brooklyn",              zip: '97202', area: 'SE Portland',     avgCost: 7900,  range: '$5.5k–$11k', commonMaterial: 'Asphalt',          indexPct: 60,  description: 'Affordable SE neighbourhood undergoing gradual gentrification with cost-conscious homeowners.', highlights: ['Value market — standard 3-tab or architectural shingle fits budget', 'Many homes have deferred maintenance — inspect deck condition', 'Good access for contractors from SE industrial area'] },
  { slug: 'buckman',            name: "Buckman",               zip: '97214', area: 'Inner SE',        avgCost: 8300,  range: '$6k–$11.5k', commonMaterial: 'Asphalt',          indexPct: 63,  description: 'Dense inner SE neighbourhood with urban housing and commercial mix, popular with younger homeowners.', highlights: ['Urban density — debris containment essential', 'Flat and low-slope sections common on older commercial-residential mix', 'Active permit office: budget 2–3 weeks for approval'] },
  { slug: 'kerns',              name: "Kerns",                 zip: '97214', area: 'Inner SE',        avgCost: 8100,  range: '$5.8k–$11k', commonMaterial: 'Asphalt',          indexPct: 61,  description: 'Transitional inner SE neighbourhood with a mix of residential and light commercial properties.', highlights: ['Growing homeowner investment in the area', 'Mix of flat and pitched roofs requires versatile contractor', 'Watch for undetected water damage in older stock'] },

  // ── Inner NE ──
  { slug: 'lloyd-district',     name: "Lloyd District",        zip: '97232', area: 'Inner NE',        avgCost: 7800,  range: '$5.5k–$10.5k',commonMaterial: 'Flat / TPO',       indexPct: 59,  description: 'Commercial-heavy district with residential pockets and a high proportion of flat commercial roofs.', highlights: ['Predominantly flat commercial roofing', 'Residential pockets use standard asphalt', 'Strong commercial contractor presence — check residential experience'] },
  { slug: 'sullivans-gulch',    name: "Sullivan's Gulch",      zip: '97232', area: 'Inner NE',        avgCost: 8500,  range: '$6k–$12k',   commonMaterial: 'Asphalt',          indexPct: 64,  description: 'Linear residential neighbourhood between Lloyd District and Irvington with steady housing demand.', highlights: ['Good mix of single-family homes entering re-roof cycle', 'Freeway proximity: budget extra for debris protection', 'Transitional area with improving homeowner investment'] },
  { slug: 'irvington',          name: "Irvington",             zip: '97212', area: 'NE Portland',     avgCost: 10800, range: '$8k–$15k',   commonMaterial: 'Asphalt Premium',  indexPct: 82,  description: 'Historic NE neighbourhood with large Craftsman homes and an active landmark district driving premium roofing decisions.', highlights: ['Portland Landmark Survey area — material choices matter', 'Large homes with complex rooflines add to cost', 'Premium market: many homeowners invest in 50-year materials'] },
  { slug: 'alameda',            name: "Alameda",               zip: '97212', area: 'NE Portland',     avgCost: 11500, range: '$9k–$16k',   badge: 'hot', commonMaterial: 'Cedar / Premium',  indexPct: 87,  description: 'One of Portland\'s most sought-after neighbourhoods with large historic homes on the Alameda Ridge.', highlights: ['Elevated ridge location — high wind exposure year-round', 'Cedar shake common and expected by the market', 'Premium pricing justified: buyers expect top-quality roofs'] },
  { slug: 'beaumont-wilshire',  name: "Beaumont-Wilshire",     zip: '97212', area: 'NE Portland',     avgCost: 10200, range: '$8k–$14k',   commonMaterial: 'Asphalt Premium',  indexPct: 77,  description: 'Established NE neighbourhood with solid housing values and homeowners investing in long-term upgrades.', highlights: ['Strong investment market — metal roofing gaining traction', 'Alberta St commercial anchor drives neighbourhood pride', 'Good contractor access via major arterials'] },

  // ── NE Portland ──
  { slug: 'grant-park',         name: "Grant Park",            zip: '97212', area: 'NE Portland',     avgCost: 9900,  range: '$7.5k–$14k', commonMaterial: 'Asphalt Premium',  indexPct: 75,  description: 'Family-focused NE neighbourhood adjacent to Grant Park with strong school districts and homeowner stability.', highlights: ['Stable long-term owners re-roofing after 25-30 years', 'Tree canopy: moss prevention with zinc strips recommended', 'Above-average spend willingness for durable materials'] },
  { slug: 'hollywood',          name: "Hollywood",             zip: '97213', area: 'NE Portland',     avgCost: 8700,  range: '$6.5k–$12k', commonMaterial: 'Asphalt',          indexPct: 66,  description: 'Commercial hub district with surrounding residential and steady demand across all project sizes.', highlights: ['Commercial and residential mix — versatile contractor needed', 'Max Line construction zone: confirm contractor access', 'Mid-market pricing suits variety of budgets'] },
  { slug: 'sabin',              name: "Sabin",                 zip: '97217', area: 'NE Portland',     avgCost: 9000,  range: '$7k–$12.5k', commonMaterial: 'Asphalt',          indexPct: 68,  description: 'Close-knit NE neighbourhood with excellent access and strong community standards for home maintenance.', highlights: ['Active neighbourhood association with high standards', 'Classic bungalow stock ideal for 30-year architectural shingles', 'Good contractor competition keeps quotes fair'] },
  { slug: 'concordia',          name: "Concordia",             zip: '97211', area: 'NE Portland',     avgCost: 8200,  range: '$6k–$11.5k', commonMaterial: 'Asphalt',          indexPct: 62,  description: 'Diverse NE neighbourhood with a mix of housing types and a steady re-roofing market.', highlights: ['Variety of roof types across housing stock', 'Value-conscious market with growing investment', 'NE access makes contractor scheduling straightforward'] },

  // ── N Portland ──
  { slug: 'cully',              name: "Cully",                 zip: '97218', area: 'NE Portland',     avgCost: 7600,  range: '$5.5k–$10.5k',badge: 'new', commonMaterial: 'Asphalt',          indexPct: 57,  description: 'Portland\'s largest neighbourhood by area, rapidly improving with new homeowner investment and growing roofing demand.', highlights: ['Fastest-growing re-roofing demand in NE Portland', 'Large lots with trees — gutter guard upsell opportunity', 'Value market: standard architectural shingle optimal'] },
  { slug: 'alberta-arts-district', name: "Alberta Arts District", zip: '97217', area: 'NE Portland',  avgCost: 8800,  range: '$6.5k–$12k', commonMaterial: 'Asphalt',          indexPct: 66,  description: 'Vibrant arts-focused corridor with strong residential demand and community-conscious homeowners.', highlights: ['Community pride drives above-average maintenance standards', 'Older bungalows on active re-roof cycle', 'Strong word-of-mouth referral culture — quality work pays off'] },
  { slug: 'mississippi-ave',    name: "Mississippi Avenue",    zip: '97217', area: 'N Portland',      avgCost: 9100,  range: '$7k–$12.5k', commonMaterial: 'Asphalt',          indexPct: 69,  description: 'Revitalised N Portland corridor with rapidly appreciating home values driving roofing investment.', highlights: ['Rising property values increase willingness to invest in roofs', 'Dense urban housing with tight access', 'Growing demand: project lead times increasing in 2026'] },
  { slug: 'overlook',           name: "Overlook",              zip: '97217', area: 'N Portland',      avgCost: 8400,  range: '$6k–$11.5k', commonMaterial: 'Asphalt',          indexPct: 64,  description: 'N Portland neighbourhood on the bluff above the Willamette with a mix of bungalows and ranch-style homes.', highlights: ['Elevated position increases wind exposure slightly', 'Bluff homes may require extra safety equipment — check with contractor', 'Solid mid-market with consistent demand'] },
  { slug: 'piedmont',           name: "Piedmont",              zip: '97217', area: 'N Portland',      avgCost: 7900,  range: '$5.8k–$10.8k',commonMaterial: 'Asphalt',          indexPct: 60,  description: 'Affordable N Portland neighbourhood with many long-time owners now in re-roofing decision windows.', highlights: ['High proportion of homes 25–35 years old — prime re-roof market', 'Value-oriented: position asphalt as the smart long-term choice', 'Less contractor competition than inner eastside'] },
  { slug: 'arbor-lodge',        name: "Arbor Lodge",           zip: '97217', area: 'N Portland',      avgCost: 8000,  range: '$5.8k–$11k', commonMaterial: 'Asphalt',          indexPct: 60,  description: 'Tree-canopy-rich N Portland neighbourhood with mature housing stock and growing homeowner investment.', highlights: ['Dense tree canopy: debris management and gutter guards important', 'Ranch and bungalow mix — generally simpler rooflines', 'Growing gentrification driving investment in quality roofing'] },
  { slug: 'kenton',             name: "Kenton",                zip: '97217', area: 'N Portland',      avgCost: 7700,  range: '$5.5k–$10.5k',commonMaterial: 'Asphalt',          indexPct: 58,  description: 'Historic N Portland neighbourhood with an expanding arts and food scene attracting new homeowners.', highlights: ['New homeowners discovering deferred maintenance', 'Bungalow stock with straightforward roof geometries', 'Competitive contractor market: multiple quotes recommended'] },

  // ── N Portland ──
  { slug: 'st-johns',           name: "St. Johns",             zip: '97203', area: 'N Portland',      avgCost: 7900,  range: '$5.5k–$11k', commonMaterial: 'Asphalt',          indexPct: 60,  description: 'Rapidly evolving N Portland neighbourhood with new homeowner investment driving roofing demand above expectations.', highlights: ['One of Portland\'s fastest-improving neighbourhoods', 'Bridge-adjacent: some wind exposure consideration', 'Value-first market with upward mobility'] },
  { slug: 'portsmouth',         name: "Portsmouth",            zip: '97203', area: 'N Portland',      avgCost: 7500,  range: '$5.2k–$10k', commonMaterial: 'Asphalt',          indexPct: 57,  description: 'Established N Portland neighbourhood with affordable housing and increasing homeowner improvement activity.', highlights: ['Budget-conscious market: keep proposals clear and value-focused', 'Ranch homes with low-slope sections common', 'Less contractor saturation — good opportunity zone'] },
  { slug: 'cathedral-park',     name: "Cathedral Park",        zip: '97203', area: 'N Portland',      avgCost: 7800,  range: '$5.5k–$10.5k',commonMaterial: 'Asphalt',          indexPct: 59,  description: 'Scenic N Portland neighbourhood below the St. Johns Bridge with a mix of housing types and steady demand.', highlights: ['River proximity: moisture load higher than inner east side', 'Tourism destination — neighbourhood pride matters', 'Mixed old/new stock: condition assessment critical'] },
  { slug: 'university-park',    name: "University Park",       zip: '97203', area: 'N Portland',      avgCost: 8100,  range: '$6k–$11.5k', commonMaterial: 'Asphalt',          indexPct: 61,  description: 'Stable residential neighbourhood surrounding University of Portland with consistent homeowner investment.', highlights: ['Academic community drives careful, research-based decisions', 'Well-maintained housing stock — mostly preventative/replacement', 'Good access from N Portland corridor'] },
  { slug: 'linnton',            name: "Linnton",               zip: '97231', area: 'N Portland',      avgCost: 7400,  range: '$5k–$10k',   commonMaterial: 'Asphalt',          indexPct: 56,  description: 'Small industrial-residential neighbourhood along the Willamette with unique access considerations.', highlights: ['River road access can limit equipment staging', 'Industrial adjacency: heavier moss and debris accumulation', 'Smaller market — ensure contractor is comfortable with access'] },

  // ── West Portland ──
  { slug: 'forest-park',        name: "Forest Park",           zip: '97229', area: 'NW Portland',     avgCost: 12800, range: '$10k–$20k',  badge: 'hot', commonMaterial: 'Cedar / Metal',    indexPct: 97,  description: 'Exclusive hillside neighbourhood adjacent to the country\'s largest urban forest. High-end homes demand specialist contractors.', highlights: ['Highest wind exposure in Portland metro', 'Cedar shake and metal roof — mandatory for many homes', 'Limited contractor access: specialist firms only recommended'] },
  { slug: 'west-hills',         name: "West Hills",            zip: '97225', area: 'West Portland',   avgCost: 13200, range: '$10.5k–$22k', commonMaterial: 'Cedar / Metal',    indexPct: 100, description: 'Portland\'s most prestigious residential area with large estates requiring specialist roofing and maximum material quality.', highlights: ['Premium market — second only to Lake Oswego', 'Extreme slope roofs common: safety costs higher', 'Viewsheds and HOA rules may restrict material choices'] },
  { slug: 'council-crest',      name: "Council Crest",         zip: '97201', area: 'SW Portland',     avgCost: 12400, range: '$9.5k–$19k', commonMaterial: 'Cedar / Metal',    indexPct: 94,  description: 'Hilltop neighbourhood at Portland\'s highest point with outstanding views and significant wind exposure.', highlights: ['Highest elevation in Portland: significant wind uplift risk', 'Premium material investment strongly recommended', 'Complex roof geometry on many estate homes'] },
  { slug: 'sylvan-highlands',   name: "Sylvan-Highlands",      zip: '97225', area: 'SW Portland',     avgCost: 11800, range: '$9k–$17k',   commonMaterial: 'Asphalt Premium',  indexPct: 89,  description: 'Quiet hillside neighbourhood between the West Hills and Beaverton with executive homes and premium roofing demand.', highlights: ['Hillside access: some properties require specialised rigging', 'Above-average spend: homeowners invest in 40–50 year materials', 'Low contractor density: book 6–8 weeks in advance'] },
  { slug: 'multnomah-village',  name: "Multnomah Village",     zip: '97219', area: 'SW Portland',     avgCost: 10400, range: '$8k–$14k',   badge: 'hot', commonMaterial: 'Asphalt Premium',  indexPct: 79,  description: 'Popular SW Portland village with strong community identity and above-average homeowner investment.', highlights: ['Community focus drives referral culture', 'Mix of mid-century and Craftsman homes on re-roof cycle', 'Competitive SW market: get 3+ quotes'] },

  // ── Metro / Suburbs ──
  { slug: 'beaverton',          name: "Beaverton",             zip: '97005', area: 'Washington Co.',  avgCost: 8600,  range: '$6.5k–$12k', commonMaterial: 'Asphalt',          indexPct: 65,  description: 'Oregon\'s second-largest city with a booming tech corridor and high volume of residential re-roofing demand.', highlights: ['High volume market: contractor availability generally good', 'Mix of 1980s–90s suburban stock entering re-roof cycle', 'Washington County permits — different process to PDX city'] },
  { slug: 'hillsboro',          name: "Hillsboro",             zip: '97006', area: 'Washington Co.',  avgCost: 8300,  range: '$6k–$11.5k', commonMaterial: 'Asphalt',          indexPct: 63,  description: 'Fast-growing tech hub city with large suburban housing stock and increasing roofing demand from new homeowners.', highlights: ['Intel and semiconductor campus proximity: strong income base', 'New construction alongside aging 90s suburban stock', 'Competitive market: multiple regional contractors active'] },
  { slug: 'gresham',            name: "Gresham",               zip: '97030', area: 'E Multnomah Co.', avgCost: 7900,  range: '$5.5k–$11k', commonMaterial: 'Asphalt',          indexPct: 60,  description: 'Oregon\'s fourth-largest city with a large and diverse housing stock representing a broad roofing market.', highlights: ['Value-oriented market: cost-per-sq-ft messaging effective', 'Large suburban lots with older 1970s–80s housing', 'MAX Light Rail access makes scheduling easier for contractors'] },
  { slug: 'lake-oswego',        name: "Lake Oswego",           zip: '97034', area: 'Clackamas Co.',   avgCost: 12400, range: '$9.5k–$19k', badge: 'hot', commonMaterial: 'Metal / Cedar',    indexPct: 94,  description: 'Portland\'s premier lakeside suburb with luxury homes, high incomes, and a market that demands the best roofing money can buy.', highlights: ['Highest average project value in the metro after West Hills', 'Lake proximity drives moisture load and premium material choice', 'HOA rules in many neighbourhoods restrict materials and colours'] },
  { slug: 'tigard',             name: "Tigard",                zip: '97223', area: 'Washington Co.',  avgCost: 8700,  range: '$6.5k–$12k', commonMaterial: 'Asphalt',          indexPct: 66,  description: 'Established SW suburb with a mix of housing types and strong contractor competition keeping prices fair.', highlights: ['Good contractor coverage from both Portland and Beaverton firms', '1970s–80s suburban ranches well into re-roof window', 'Value market: architectural shingle offers best ROI'] },
  { slug: 'west-linn',          name: "West Linn",             zip: '97068', area: 'Clackamas Co.',   avgCost: 11900, range: '$9k–$18k',   commonMaterial: 'Asphalt Premium',  indexPct: 90,  description: 'Affluent Clackamas County suburb with large homes, high homeowner investment, and premium roofing expectations.', highlights: ['Willamette River bluffs increase wind exposure', 'Executive homes with complex roof geometry', 'Premium market: quality asphalt or metal both well-received'] },
  { slug: 'oregon-city',        name: "Oregon City",           zip: '97045', area: 'Clackamas Co.',   avgCost: 8200,  range: '$6k–$11.5k', commonMaterial: 'Asphalt',          indexPct: 62,  description: 'Historic Oregon capital with a mix of Victorian-era homes and suburban stock representing diverse roofing needs.', highlights: ['Historic downtown area has older, steeper-pitched roofs', 'Clackamas County permits: budget extra lead time', 'Growing market as families move south from Portland'] },
  { slug: 'milwaukie',          name: "Milwaukie",             zip: '97222', area: 'Clackamas Co.',   avgCost: 8100,  range: '$6k–$11k',   commonMaterial: 'Asphalt',          indexPct: 61,  description: 'Riverside suburb south of Portland with strong homeowner community and consistent roofing demand.', highlights: ['MAX Orange Line access: easy contractor staging', '1960s–70s ranch stock heavily in re-roof cycle', 'Competitive mid-market pricing'] },
]

export function getNeighborhoodBySlug(slug: string): Neighborhood | undefined {
  return neighborhoods.find(n => n.slug === slug)
}

export function getStaticNeighborhoodPaths() {
  return neighborhoods.map(n => ({ neighborhood: n.slug }))
}
